name: 'Commit Message Enforcement'
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(?:BREAKING CHANGE: )?(feat|fix|refactor|chore|test|rm): \w'
          error: 'Your commit must follow the pattern: ^(?:BREAKING CHANGE: )?(feat|fix|refactor|chore|test|rm): \w'
