name: Lint

on:
  push:
    branches: [ master ]
  pull_request:

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: 'npm'
      - name: Install Dependencies
        run: make install-dev
      - name: Lint
        run: make lint
