name: Release
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: '${{ matrix.platform }}'
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: npm
      - name: Install Dependencies (Ubuntu Only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt update 
          sudo apt install libssl-dev libwebkit2gtk-4.0-dev build-essential curl wget libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev 
          make install-dev
      - name: Install Dependencies (macOS & Windows)
        if: matrix.platform != 'ubuntu-latest'
        run: make install-dev
      - name: Build
        run: make build
      - name: Prepare Tauri Environment
        run: cargo install tauri-cli
      - name: Build & Package (Windows Only)
        if: matrix.platform == 'windows-latest'
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        run: make package-windows
      - name: Build & Package (macOS Only)
        if: matrix.platform == 'macos-latest'
        env:
          ENABLE_CODE_SIGNING: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        run: make package-macos
      - name: Build & Package (Linux Only)
        if: matrix.platform == 'ubuntu-latest'
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        run: make package-linux-amd64
      - name: Upload Artifacts (Linux Only)
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: Linux Packages
          path: |
            /home/runner/work/syng/syng/src/native/target/x86_64-unknown-linux-gnu/release/bundle/
      - name: Upload Artifacts (macOS Only)
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: macOS Packages
          path: |
            /Users/runner/work/syng/syng/src/native/target/x86_64-apple-darwin/release/bundle/
            /Users/runner/work/syng/syng/src/native/target/aarch64-apple-darwin/release/bundle/
      - name: Upload Artifacts (Windows Only)
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: Windows Packages
          path: |
            D:\a\syng\syng\src\native\target\x86_64-pc-windows-msvc\release\bundle/msi/
            D:\a\syng\syng\src\native\target\i686-pc-windows-msvc\release\bundle/msi/
